# Site
repository: dydevel/modern-resume-theme.git
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: David Young
title: Full Stack Software Developer
email: daveyoung80@gmail.com
# website: https://dydevel.github.io/cv-site

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  dydevel
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: "544190085"
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: david-young-6263751
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
gtag: "G-919GQCF23L"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile-bw.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm a highly experienced Full Stack Java and React Developer with approaching 20 years of commercial development experience across many sectors. 
  I have a thirst for technology and a drive to seek better, more efficient solutions using the best tools for each situation.
  Significant experience in developing highly scalable, reliable solutions in the cloud using AWS and a big advocate for Agile methodologies.

content:
  - title: Core Skills # Title for the section
    layout: text # Type of content section (list/text)
    content:
      <table id="core-skills-table">
        <tr>
          <td>
            <h4>Backend</h4>
            Java 17, Spring Boot, Hibernate / JPA, NodeJS, RDBMS, Kafka, Microservices
          </td>
          <td>
            <h4>Platforms</h4>
            Kubernetes, Docker
          </td>
          <td>
            <h4>Databases</h4>
            Oracle, MySql, Postgres, Mongo, Elastic Search
          </td>
        </tr>

      <tr>
        <td>
          <h4>Frontend</h4>
          Javascript, React, HTML, CSS, Jest, Mocha, NPM, Yarn
        </td>
        <td>
          <h4>Cloud</h4>
          AWS, Terraform
        </td>
        <td>
          <h4>Build / Deployment</h4>
          CI/CD, Jenkins, GitHub Actions, Ansible
        </td>
      </tr>

      <tr>
      <td>
        <h4>Source Control</h4>
        Git, GitHub, GitLab, Bitbucket
      </td>
      <td>
        <h4>Process</h4>
        Agile, Scrum, Kanban, Jira
      </td>
      </tr>
      </table>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    show-first: 4
    content:
      - layout: left
        title: PPS
        link: https://www.pps.edenred.com/
        sub_title: Software Developer (Contract)
        caption: November 2022 - Present
        quote: >
          Java 17, Spring Boot, Docker/ Docker Swarm, Oracle, AWS, Jenkins, Ansible, Bitbucket
        description: | # this will include new lines to allow paragraphs
          Joined a new scrum team responsible for building a new microservice solution that will form an integral part of PPS' payment systems, enabling
          realtime fraud and money laundering detection.
          * Implemented a high performance data transformation / adapter service 
          * Integrated with the Featurespace ARIC events API
          * Worked closely with platform engineers to setup build pipelines using AWS Code Build, Ansible and Jenkins
          * Worked closely with QA engineers building automated testing frameworks

      - layout: left
        title: GoDaddy
        link: godaddy.com
        sub_title: Software Developer (Contract)
        caption: April 2022 - October 2022
        quote: >
          Java 11, Spring Boot, MySQL, Docker, AWS (ECS, Secrets Manager), NodeJS, Jenkins, K8s, Github
        description: | # this will include new lines to allow paragraphs
          Joined an existing fully remote scrum team developing new microservice APIs for handling customer baskets in an existing e-commerce web application.
          * Led on the development of the basket migration feature - enabling seamless migration of customer data from the live legacy system
          * Introduced Junit 5 features improving maintainability of unit tests whilst improving test coverage
          * Mentored junior team members through code reviews and pairing sessions
          * Worked closely with QA engineers to triage bugs

      - layout: left
        title: Elsevier
        link: elsevier.com
        sub_title: Software Engineering Lead (Permanent)
        caption: January 2021 - April 2022
        quote: >
          Java 11, Spring Boot, React, Kafka, RDS / Postgres, Docker, AWS (EKS, S3, CloudFront, WAF), Jenkins, Spinnaker, Cypress
        description: | # this will include new lines to allow paragraphs
          Led a new fully remote, scrum team composed of permanent staff and offshore contractors, building from the ground up, an event driven microservice framework and UIs for curating data and supporting ML data pipelines.
          * Worked closely with product owners and architects on the overall design of the framework, ensuring a robust application and enabling future reuse across the business.
          * Designed and oversaw the development of micro-frontend UIs for actioning data curation tasks.
          * Designed and co-developed a new CI/CD pipeline ensuring deployed code was fully tested and exceeded required quality standards - integrating with tools such as SonarQube and Contrast
          * Mentored junior team members through code reviews ensuring that the application code, business logic and tests were to the highest standards.

      - layout: left
        title: Blackcat Technology Solutions
        link: https://uk.linkedin.com/company/blackcat-solutions-ltd
        link_text: (LinkedIn Profile)
        sub_title: Application Architect (Permanent)
        caption: November 2013 - January 2021
        description: | # this will include new lines to allow paragraphs
          Blackcat was an agile software development consultancy, serving both large and small organisations, providing expert software delivery teams producing cutting edge custom technology solutions. 
          I was involved in numerous and varied projects.
          
          Blackcat ceased trading January 2021.   
                    
          **Project - Elsevier - Open Access (4 months)**
          
          I joined an existing scrum team on a long running project involving the development of several key public facing web applications. I worked on the development of new application features including updating the existing UI flows, replacing legacy code and integration involving Elsevier’s internal payment and invoicing systems. I worked closely with product owners and technical leads to drive improvements to customer user journeys and expand available payment options driving an increase in market share in the Chinese market. I left the project as Blackcat ended its operations, and was immediately hired in a permanent tech lead role in another division of the business.
          <p class="quote">Java 11, Spring Boot, ReactJs, Bootstrap, AWS Cloud Formation, Postgres, Jenkins, Serenity</p>
          
          **Project - Proagrica MDM (8 months)**
          
          Myself and a small team of Blackcat consultants started a greenfield project tasked with designing a taxonomy and data lake for storing CRM and product catalogue data. I was primarily involved in the UX design and development of a new single page web application for identifying and maintaining links between similar customer products. I was also responsible for developing REST APIs providing the application data layer for the data lake. This project provided a strong foundation for future data lake backed services providing potentially transformational new business capabilities.
          <p class="quote">ReactJs, Material UI, Java 11, Spring Boot, K8s, AWS, Jenkins</p>

          **Project - Elsevier PPE (18 months)**
          
          I was the technical lead of a large scrum team assigned with the task of developing a UI and associated services for compiling articles into journals - the first part of a programme of work to modernise the systems involved in journal production. The solution introduced a new microservice architecture and a new React based single page web application. Deployment was via a new continuous delivery pipeline - a first for Elsevier. I worked closely with the product owner and solution architect to lead the design of the technical solution. The foundational work we produced for this project has provided the foundation for several further projects, and has significantly reduced the burden of journal issue compilation for journal managers, reducing time to publication and providing significant cost savings for Elsevier.
          <p class="quote">Java 11, Spring Boot, ReactJs, Redux, Pact, K8s, MongoDB, Serenity</p>  
          
          **Project - Informed 360 (6 months)**
             
          I was a member of a small scrum team delivering an innovative compliance web application product for a small startup. I was involved in developing new functionality for user stories, optimisation of AWS deployment infrastructure and development of the CI/CD pipeline.
          <p class="quote">Java 8, Spring Boot, ReactJs, Redux, Terraform, Docker, AWS</p>   
          
          **Project - Deb Group (9 months)**
 
          I was taken on to support a lone internal developer in completing, improving and productionising an Internet-Of-Things Spring Boot backed dashboard web application. My work included web application development - implementing dashboard widgets & charting, the dockerization & deployment of the application in the cloud and also the development of a CI pipeline
          <p class="quote">Java 8, Spring Boot, Backbone JS, D3.js, Docker, AWS</p>
          
          **Project - Thomson Reuters - Regulatory Intelligence (2 years, 10 months)**
  
          Initially Joined a scrum team working to add new features to a single page web application written in Java and Dojo UI.
          * Became Scrum Master / Tech Lead a Team working on XSLT document transformations.
          * Designed and Implemented a solution for on-the-fly pagination of large XML documents.
          * Designed and built a test data generation framework
          <p class="quote">Java 8, Spring, XML, XSLT, Dojo, Gatling / Scala, Dojo, ELK stack</p>

      - layout: left
        title: SCISYS UK
        sub_title: Senior Applications Developer
        caption: February 2008 – November 2013
        quote: >
          Java 6, JEE 5, EJB 3.0, JAX-WS, JAX-B, JSF, IBM Websphere AS / Process Server, Jasper Reports, Spring
        description: |
          Working within the environment division, I was involved in the development of several large projects including the IBM Beacon Award finalist ‘Inferis’ application for the Coal Authority. 
          Inferis was a large integrated JEE web application providing public facing forms and services for logging orders for mining reports and permits,
          back office workflow driven processes for producing reports, managing assets and spatial data.

      - layout: left
        title: Andrew Network Solutions
        sub_title: Java Developer
        caption: January 2005 – February 2008
        quote: >
          Java, J2EE, JSP, Tomcat, SQL, Oracle, GIS / MapInfo
        description: |
          I worked my way up from a Junior Developer within a few months of starting at Andrew, and made a name for myself as a hardworking, 
          knowledgeable and dependable member of the development team.  XSP (eXtensible Solutions Platform) was a highly modular, customisable,
          performance optimised form based web application platform.

      - layout: left
        title: Cintra UK Ltd
        sub_title: Development Consultant
        caption: January 2005 – October 2005
        quote: >
          Java, J2EE, JSP, Servlets Tomcat, SQL

      - layout: left
        title: South Oxfordshire DC
        sub_title: ICT Development Officer
        caption: June 2003 – December 2004
        quote: >
          Java, HTML, CSS, Javascript

  - title: Qualifications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Professional Scrum Master PSM I
        caption: October 2016

      - layout: top-middle
        title: University of Leeds
        sub_title: 2:1 BSc Hons Computer Science
        caption: 1999 – 2002

      - layout: top-middle
        title: Woodford Lodge Sixth Form
        sub_title: A Levels - Physics (A), Mathematics (B), General Studies (B), Fine Art (C)
        caption: 1997 – 1999

      - layout: top-middle
        title: Woodford Lodge High School
        sub_title: GCSEs - 4A*s (Double Award Science, Art, Design and Technology), 3A's (Maths, French, Geography), 2B's (English Language and Literature
        caption: 1995 – 1997

  - title: Hobbies and Interests
    layout: text
    content: | # this will include new lines to allow paragraphs
      I’m a husband and hands on Dad to a Son and Daughter aged 11 and 6 respectively. 
      When not ferrying children to clubs and lessons, I enjoy playing guitar, and generally enjoy all things guitar related. 
      I have an interest in motorsports and cars in general.  I’m often found up a ladder ‘DIY-ing’ at the weekend.  
      I enjoy exercising - I’m a regular at the gym, plus I jog and cycle when time and weather allow.

  - title: LinkedIn Recommendations # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Maksym Shamanov
        sub_title: Scrum teammate At GoDaddy
        caption: October 19, 2022
        description: Worked with David in one team at GoDaddy. It was a great experience for me to work with so experienced and knowledgeable colleague who always open to share his knowledge and ready to help.

      - layout: top-middle
        title: Michal Pochowski
        sub_title: Scrum Team Lead At GoDaddy
        caption: October 6, 2022
        description: David had worked for Catalog team at GoDaddy over the last 6 months. He proven that he is highly skilled and experienced developer, that every manager would like to have in their team. His approach to the task given was always professional and reliable. David was also sharing his knowledge with the other team members, contributing to better code quality and suggesting alternative technologies. I definitely recommend David, I have nothing but positive thoughts about my cooperation with David at GoDaddy.

      - layout: top-middle
        title: Andy White
        sub_title: Tech Lead at Blackcat / Elsevier
        caption: March 15, 2019
        description: David and I worked very closely together in a development team for Elsevier (a client of BlackCat). He is a very knowledgeable and technically superb java developer and architect. Not only that but his gentle unassuming character means that he is very easy to work and get along with. The combination of his knowledge and character mean that he is an excellent leader who is worth listening to and being guided by. I thoroughly enjoyed working with him and don't hesitate to recommend him.

      - layout: top-middle
        title: Conor O'Neill
        sub_title: Architect at Andrew Network Solutions
        caption: February 12, 2008
        description: Dave is an extremely capable developer, with a great grasp of technology and a deep understanding of how to implement solutions for real-world problems. A valued member of any team, willing to contribute actively in design meetings, and he can also be relied upon to work well alone if needed. I would certainly recommend Dave's work.

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: dydevel/modern-resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
